### ISSUE TITLE
How to fix the "popping" in music

### ISSUE THREAD

**Issue by robin-raymond** [martinpiper/C64Public#8]
[storm.zip](https://github.com/user-attachments/files/16561634/storm.zip)

When I play the song using Music Studio, the filter will "pop" "click" every so often, especially on the long notes. I'm unclear how to fix. Do you have suggestions?

**Comment by martinpiper** [comment]
It was the Pulse Table causing the pop. Probably because the looping pulse table entries were always adding a value to the pulse width, which will eventually overflow.
I added a subtract pulse width command which produces an oscillating sound.
![image](https://github.com/user-attachments/assets/d6ff8856-1cc3-4cc7-8f89-4b60c5213b9d)

**Comment by robin-raymond** [comment]
Just for clarification, did you change code in the studio, or should I change a setting? I'm not familiar how the pulse/note/wave tables actually work.

**Comment by martinpiper** [comment]
Change the pulse table in the editor. Where the screenshot indicates.
